### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by beckermr**
This PR does the rebuild. Closes #13 Closes #12

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge/limix-inference, this rebuild PR is ready to merge. 

FWIW, this package appears largely deprecated. I don't think there is an official policy and/or method on how to deprecate packages. If you want to, I would ping the core dev team for guidance. 

Otherwise, we can merge this PR and continue to support what we can of this package.

**Comment by beckermr** [comment]
Bump @conda-forge/limix-inference

**Comment by horta** [comment]
Hi @beckermr , thanks for the feedback. I believe this package can be flagged as deprecated safely. Please, go ahead if you wish.

**Pull request merged**
